//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.17929
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADUserEditorWebpart.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ADUserEditorWebpart {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ADUserEditorWebpart() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADUserEditorWebpart.Resources.ADUserEditorWebpart", typeof(ADUserEditorWebpart).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Apply.
        /// </summary>
        internal static string lgApply {
            get {
                return ResourceManager.GetString("lgApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string lgCancel {
            get {
                return ResourceManager.GetString("lgCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear.
        /// </summary>
        internal static string lgClear {
            get {
                return ResourceManager.GetString("lgClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration.
        /// </summary>
        internal static string lgConfiguration {
            get {
                return ResourceManager.GetString("lgConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AD User Editor needs to be configured.
        /// </summary>
        internal static string lgConfigurationNeeded {
            get {
                return ResourceManager.GetString("lgConfigurationNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;properties&gt;&lt;property adname=&apos;displayName&apos; name=&apos;Full Name&apos; type=&apos;readonly&apos; /&gt;&lt;property adname=&apos;thumbnailPhoto&apos; name=&apos;Photo&apos; type=&apos;image&apos; /&gt;&lt;property adname=&apos;sn&apos; name=&apos;Last Name&apos; type=&apos;textbox&apos; /&gt;&lt;property adname=&apos;givenName&apos; name=&apos;First Name&apos; type=&apos;textbox&apos; /&gt;&lt;property adname=&apos;manager&apos; name=&apos;Manager&apos; type=&apos;person&apos; /&gt;&lt;property adname=&apos;assistant&apos; name=&apos;Assistant&apos; type=&apos;person&apos; /&gt;&lt;property adname=&apos;department&apos; name=&apos;Service&apos; type=&apos;listbox&apos; values=&quot;IT;Human Resources;Bio;Security&quot; /&gt;&lt;property adname=&apos;title&apos; name [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string lgDefaultPropertiesConf {
            get {
                return ResourceManager.GetString("lgDefaultPropertiesConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Active Directory Controller(s).
        /// </summary>
        internal static string lgDomainControllers {
            get {
                return ResourceManager.GetString("lgDomainControllers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Editing has been cancelled!.
        /// </summary>
        internal static string lgEditCancelled {
            get {
                return ResourceManager.GetString("lgEditCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  (Max. 2 Mo, Jpeg only, will be resized to 128x128px).
        /// </summary>
        internal static string lgImgConstraints {
            get {
                return ResourceManager.GetString("lgImgConstraints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Image too large (&gt;2 Mo).
        /// </summary>
        internal static string lgImgTooLarge {
            get {
                return ResourceManager.GetString("lgImgTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wrong image format : .
        /// </summary>
        internal static string lgImgWrongFormat {
            get {
                return ResourceManager.GetString("lgImgWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User Properties.
        /// </summary>
        internal static string lgPropertiesDefinition {
            get {
                return ResourceManager.GetString("lgPropertiesDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select an User to Edit.
        /// </summary>
        internal static string lgSelectUserToEdit {
            get {
                return ResourceManager.GetString("lgSelectUserToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit current user only.
        /// </summary>
        internal static string lgSelfService {
            get {
                return ResourceManager.GetString("lgSelfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User found!.
        /// </summary>
        internal static string lgUserFound {
            get {
                return ResourceManager.GetString("lgUserFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User not found!.
        /// </summary>
        internal static string lgUserNotFound {
            get {
                return ResourceManager.GetString("lgUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a valid name!.
        /// </summary>
        internal static string lgUserNotSelected {
            get {
                return ResourceManager.GetString("lgUserNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User Selection.
        /// </summary>
        internal static string lgUserSelection {
            get {
                return ResourceManager.GetString("lgUserSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Profile updated! (24h to Sync with SharePoint).
        /// </summary>
        internal static string lgUserUpdated {
            get {
                return ResourceManager.GetString("lgUserUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select.
        /// </summary>
        internal static string lgValidate {
            get {
                return ResourceManager.GetString("lgValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AD User Editor is a WebPart that allows to edit easily any user profile attribute in Active Directory trough a customizable form. (version 2.1.4).
        /// </summary>
        internal static string WebPartDescription {
            get {
                return ResourceManager.GetString("WebPartDescription", resourceCulture);
            }
        }
    }
}
